---
# Example mainnet inventory - copy to local.yml and customize
all:
  vars:
    env: mainnet

  children:
    monad:
      children:
        validators:
          hosts:
             my-validator:
               ansible_host: "1.2.3.4"
               type: validator
               setup_triedb: true
               triedb_config:
                 path: "/dev/triedb"
               register_validator: false

        fullnodes:
          hosts: {}
